### PR TITLE
Removed no-new rule

### PR DESCRIPTION
**Pull request by MaksymShokin**
@squallstar 

## Description
Removed no-new rule as discussed here https://github.com/Fliplet/fliplet-widget-onboarding/pull/30.

### CODE REVIEW

**Comment by squallstar** [comment]
Please also update version on package and package lock so that I can release this to Npm.

**Comment by MaksymShokin** [comment]
@squallstar 
Updated version in package.json. How do I update in package lock? There is no such file here

**Comment by squallstar** [comment]
@MaksymShokin no need, package.json is sufficient. Thanks!

**Comment by squallstar** [comment]
This is now live on NPM.

**Pull request merged**
